name: festival_flutterturkiye_org
description: Flutter TÃ¼rkiye Flutter Festivali Resmi Sitesi

publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  carousel_slider: ^3.0.0
  cloud_firestore: ^1.0.3
  cupertino_icons: ^1.0.2
  expansion_tile_card: ^2.0.0
  equatable: ^2.0.0
  firebase_core: ^1.0.2
  firebase_core_web: ^1.0.2
  get_it: ^6.0.0
  material_design_icons_flutter: ^4.0.5955
  url_launcher: ^6.0.3
  video_player: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutrlint: ^2.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/activity_flow/
    - assets/images/speakers/
    - assets/images/sponsors/
    - assets/videos/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: fonts/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-ExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
